#GAOL KEEPER CONFIGURATIONS
[GoalKeeper]
goalie_id = 1					#goal kepper ID


#PLAY MAKE CONFIGURATIONS - nearest robot to ball who goaes after it
[PlayMake]
playmake_change_cost = 10.0		#changing playmake will come with some cost - sometimes its better not to change it even though our playmake is not the closest one to ball


#DEFENSE CONFIGURATIONS
[Defense]
critical_mode  = -30.0			#when the ball's X coordinate is less than this value the mode will become critical
non_threat_mode  = 30.0			#when the ball's X coordinate is greater than this value the mode will become non_threat
#else							#normal mode

critical_defense_num = 2		#number of defenses when we are in critical mode
non_threat_defense_num = 2		#number of defenses when we are in non_threat mode
normal_defense_num = 1			#number of defenses when we are in normal mode

