// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_parsian_simurosot_data_wrapper.proto
#include "stdafx.h"

#include "messages_parsian_simurosot_data_wrapper.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Header;
}  // namespace protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto
namespace protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Logs;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto ::google::protobuf::internal::SCCInfo<6> scc_info_Draws;
}  // namespace protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto
namespace protobuf_messages_5fparsian_5fsimurosot_5fdetection_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_messages_5fparsian_5fsimurosot_5fdetection_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_Frame;
}  // namespace protobuf_messages_5fparsian_5fsimurosot_5fdetection_2eproto
namespace protobuf_messages_5fparsian_5fsimurosot_5fworldmodel_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_messages_5fparsian_5fsimurosot_5fworldmodel_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_WorldModel;
}  // namespace protobuf_messages_5fparsian_5fsimurosot_5fworldmodel_2eproto
class HeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Header>
      _instance;
} _Header_default_instance_;
class DataWrapperDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DataWrapper>
      _instance;
} _DataWrapper_default_instance_;
namespace protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto {
static void InitDefaultsHeader() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Header_default_instance_;
    new (ptr) ::Header();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Header::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Header =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsHeader}, {}};

static void InitDefaultsDataWrapper() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_DataWrapper_default_instance_;
    new (ptr) ::DataWrapper();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::DataWrapper::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<5> scc_info_DataWrapper =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 5, InitDefaultsDataWrapper}, {
      &protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::scc_info_Header.base,
      &protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto::scc_info_Draws.base,
      &protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto::scc_info_Logs.base,
      &protobuf_messages_5fparsian_5fsimurosot_5fdetection_2eproto::scc_info_Frame.base,
      &protobuf_messages_5fparsian_5fsimurosot_5fworldmodel_2eproto::scc_info_WorldModel.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Header.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DataWrapper.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Header, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Header, seq_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Header, stamp_second_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Header, stamp_nsecond_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DataWrapper, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DataWrapper, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DataWrapper, draws_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DataWrapper, debugs_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DataWrapper, detection_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::DataWrapper, worldmodel_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Header)},
  { 8, -1, sizeof(::DataWrapper)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Header_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_DataWrapper_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "messages_parsian_simurosot_data_wrapper.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n-messages_parsian_simurosot_data_wrappe"
      "r.proto\032*messages_parsian_simurosot_dete"
      "ction.proto\032+messages_parsian_simurosot_"
      "worldmodel.proto\032\'messages_parsian_simur"
      "osot_debugs.proto\"B\n\006Header\022\013\n\003seq\030\001 \001(\r"
      "\022\024\n\014stamp_second\030\002 \001(\r\022\025\n\rstamp_nsecond\030"
      "\003 \001(\r\"\220\001\n\013DataWrapper\022\027\n\006header\030\001 \001(\0132\007."
      "Header\022\025\n\005draws\030\002 \001(\0132\006.Draws\022\025\n\006debugs\030"
      "\003 \001(\0132\005.Logs\022\031\n\tdetection\030\004 \001(\0132\006.Frame\022"
      "\037\n\nworldmodel\030\005 \001(\0132\013.WorldModelb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 400);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messages_parsian_simurosot_data_wrapper.proto", &protobuf_RegisterTypes);
  ::protobuf_messages_5fparsian_5fsimurosot_5fdetection_2eproto::AddDescriptors();
  ::protobuf_messages_5fparsian_5fsimurosot_5fworldmodel_2eproto::AddDescriptors();
  ::protobuf_messages_5fparsian_5fsimurosot_5fdebugs_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto

// ===================================================================

void Header::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Header::kSeqFieldNumber;
const int Header::kStampSecondFieldNumber;
const int Header::kStampNsecondFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Header::Header()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::scc_info_Header.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Header)
}
Header::Header(const Header& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&seq_, &from.seq_,
    static_cast<size_t>(reinterpret_cast<char*>(&stamp_nsecond_) -
    reinterpret_cast<char*>(&seq_)) + sizeof(stamp_nsecond_));
  // @@protoc_insertion_point(copy_constructor:Header)
}

void Header::SharedCtor() {
  ::memset(&seq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&stamp_nsecond_) -
      reinterpret_cast<char*>(&seq_)) + sizeof(stamp_nsecond_));
}

Header::~Header() {
  // @@protoc_insertion_point(destructor:Header)
  SharedDtor();
}

void Header::SharedDtor() {
}

void Header::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Header::descriptor() {
  ::protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Header& Header::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::scc_info_Header.base);
  return *internal_default_instance();
}


void Header::Clear() {
// @@protoc_insertion_point(message_clear_start:Header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&seq_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&stamp_nsecond_) -
      reinterpret_cast<char*>(&seq_)) + sizeof(stamp_nsecond_));
  _internal_metadata_.Clear();
}

bool Header::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Header)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 seq = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seq_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 stamp_second = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &stamp_second_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 stamp_nsecond = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &stamp_nsecond_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Header)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Header)
  return false;
#undef DO_
}

void Header::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 seq = 1;
  if (this->seq() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->seq(), output);
  }

  // uint32 stamp_second = 2;
  if (this->stamp_second() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->stamp_second(), output);
  }

  // uint32 stamp_nsecond = 3;
  if (this->stamp_nsecond() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->stamp_nsecond(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Header)
}

::google::protobuf::uint8* Header::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Header)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 seq = 1;
  if (this->seq() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->seq(), target);
  }

  // uint32 stamp_second = 2;
  if (this->stamp_second() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->stamp_second(), target);
  }

  // uint32 stamp_nsecond = 3;
  if (this->stamp_nsecond() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->stamp_nsecond(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Header)
  return target;
}

size_t Header::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Header)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 seq = 1;
  if (this->seq() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->seq());
  }

  // uint32 stamp_second = 2;
  if (this->stamp_second() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->stamp_second());
  }

  // uint32 stamp_nsecond = 3;
  if (this->stamp_nsecond() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->stamp_nsecond());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Header::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Header)
  GOOGLE_DCHECK_NE(&from, this);
  const Header* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Header>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Header)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Header)
    MergeFrom(*source);
  }
}

void Header::MergeFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Header)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.seq() != 0) {
    set_seq(from.seq());
  }
  if (from.stamp_second() != 0) {
    set_stamp_second(from.stamp_second());
  }
  if (from.stamp_nsecond() != 0) {
    set_stamp_nsecond(from.stamp_nsecond());
  }
}

void Header::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Header::CopyFrom(const Header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Header::IsInitialized() const {
  return true;
}

void Header::Swap(Header* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Header::InternalSwap(Header* other) {
  using std::swap;
  swap(seq_, other->seq_);
  swap(stamp_second_, other->stamp_second_);
  swap(stamp_nsecond_, other->stamp_nsecond_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Header::GetMetadata() const {
  protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DataWrapper::InitAsDefaultInstance() {
  ::_DataWrapper_default_instance_._instance.get_mutable()->header_ = const_cast< ::Header*>(
      ::Header::internal_default_instance());
  ::_DataWrapper_default_instance_._instance.get_mutable()->draws_ = const_cast< ::Draws*>(
      ::Draws::internal_default_instance());
  ::_DataWrapper_default_instance_._instance.get_mutable()->debugs_ = const_cast< ::Logs*>(
      ::Logs::internal_default_instance());
  ::_DataWrapper_default_instance_._instance.get_mutable()->detection_ = const_cast< ::Frame*>(
      ::Frame::internal_default_instance());
  ::_DataWrapper_default_instance_._instance.get_mutable()->worldmodel_ = const_cast< ::WorldModel*>(
      ::WorldModel::internal_default_instance());
}
void DataWrapper::clear_draws() {
  if (GetArenaNoVirtual() == NULL && draws_ != NULL) {
    delete draws_;
  }
  draws_ = NULL;
}
void DataWrapper::clear_debugs() {
  if (GetArenaNoVirtual() == NULL && debugs_ != NULL) {
    delete debugs_;
  }
  debugs_ = NULL;
}
void DataWrapper::clear_detection() {
  if (GetArenaNoVirtual() == NULL && detection_ != NULL) {
    delete detection_;
  }
  detection_ = NULL;
}
void DataWrapper::clear_worldmodel() {
  if (GetArenaNoVirtual() == NULL && worldmodel_ != NULL) {
    delete worldmodel_;
  }
  worldmodel_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DataWrapper::kHeaderFieldNumber;
const int DataWrapper::kDrawsFieldNumber;
const int DataWrapper::kDebugsFieldNumber;
const int DataWrapper::kDetectionFieldNumber;
const int DataWrapper::kWorldmodelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DataWrapper::DataWrapper()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::scc_info_DataWrapper.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataWrapper)
}
DataWrapper::DataWrapper(const DataWrapper& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::Header(*from.header_);
  } else {
    header_ = NULL;
  }
  if (from.has_draws()) {
    draws_ = new ::Draws(*from.draws_);
  } else {
    draws_ = NULL;
  }
  if (from.has_debugs()) {
    debugs_ = new ::Logs(*from.debugs_);
  } else {
    debugs_ = NULL;
  }
  if (from.has_detection()) {
    detection_ = new ::Frame(*from.detection_);
  } else {
    detection_ = NULL;
  }
  if (from.has_worldmodel()) {
    worldmodel_ = new ::WorldModel(*from.worldmodel_);
  } else {
    worldmodel_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:DataWrapper)
}

void DataWrapper::SharedCtor() {
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&worldmodel_) -
      reinterpret_cast<char*>(&header_)) + sizeof(worldmodel_));
}

DataWrapper::~DataWrapper() {
  // @@protoc_insertion_point(destructor:DataWrapper)
  SharedDtor();
}

void DataWrapper::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete draws_;
  if (this != internal_default_instance()) delete debugs_;
  if (this != internal_default_instance()) delete detection_;
  if (this != internal_default_instance()) delete worldmodel_;
}

void DataWrapper::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DataWrapper::descriptor() {
  ::protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DataWrapper& DataWrapper::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::scc_info_DataWrapper.base);
  return *internal_default_instance();
}


void DataWrapper::Clear() {
// @@protoc_insertion_point(message_clear_start:DataWrapper)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  if (GetArenaNoVirtual() == NULL && draws_ != NULL) {
    delete draws_;
  }
  draws_ = NULL;
  if (GetArenaNoVirtual() == NULL && debugs_ != NULL) {
    delete debugs_;
  }
  debugs_ = NULL;
  if (GetArenaNoVirtual() == NULL && detection_ != NULL) {
    delete detection_;
  }
  detection_ = NULL;
  if (GetArenaNoVirtual() == NULL && worldmodel_ != NULL) {
    delete worldmodel_;
  }
  worldmodel_ = NULL;
  _internal_metadata_.Clear();
}

bool DataWrapper::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataWrapper)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Header header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Draws draws = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_draws()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Logs debugs = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_debugs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Frame detection = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_detection()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .WorldModel worldmodel = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_worldmodel()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataWrapper)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataWrapper)
  return false;
#undef DO_
}

void DataWrapper::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataWrapper)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Header header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // .Draws draws = 2;
  if (this->has_draws()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_draws(), output);
  }

  // .Logs debugs = 3;
  if (this->has_debugs()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_debugs(), output);
  }

  // .Frame detection = 4;
  if (this->has_detection()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_detection(), output);
  }

  // .WorldModel worldmodel = 5;
  if (this->has_worldmodel()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_worldmodel(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:DataWrapper)
}

::google::protobuf::uint8* DataWrapper::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DataWrapper)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Header header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // .Draws draws = 2;
  if (this->has_draws()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_draws(), deterministic, target);
  }

  // .Logs debugs = 3;
  if (this->has_debugs()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_debugs(), deterministic, target);
  }

  // .Frame detection = 4;
  if (this->has_detection()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_detection(), deterministic, target);
  }

  // .WorldModel worldmodel = 5;
  if (this->has_worldmodel()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_worldmodel(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DataWrapper)
  return target;
}

size_t DataWrapper::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DataWrapper)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Header header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *header_);
  }

  // .Draws draws = 2;
  if (this->has_draws()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *draws_);
  }

  // .Logs debugs = 3;
  if (this->has_debugs()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *debugs_);
  }

  // .Frame detection = 4;
  if (this->has_detection()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *detection_);
  }

  // .WorldModel worldmodel = 5;
  if (this->has_worldmodel()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *worldmodel_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DataWrapper::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DataWrapper)
  GOOGLE_DCHECK_NE(&from, this);
  const DataWrapper* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DataWrapper>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DataWrapper)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DataWrapper)
    MergeFrom(*source);
  }
}

void DataWrapper::MergeFrom(const DataWrapper& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DataWrapper)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_header()) {
    mutable_header()->::Header::MergeFrom(from.header());
  }
  if (from.has_draws()) {
    mutable_draws()->::Draws::MergeFrom(from.draws());
  }
  if (from.has_debugs()) {
    mutable_debugs()->::Logs::MergeFrom(from.debugs());
  }
  if (from.has_detection()) {
    mutable_detection()->::Frame::MergeFrom(from.detection());
  }
  if (from.has_worldmodel()) {
    mutable_worldmodel()->::WorldModel::MergeFrom(from.worldmodel());
  }
}

void DataWrapper::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DataWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DataWrapper::CopyFrom(const DataWrapper& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DataWrapper)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataWrapper::IsInitialized() const {
  return true;
}

void DataWrapper::Swap(DataWrapper* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DataWrapper::InternalSwap(DataWrapper* other) {
  using std::swap;
  swap(header_, other->header_);
  swap(draws_, other->draws_);
  swap(debugs_, other->debugs_);
  swap(detection_, other->detection_);
  swap(worldmodel_, other->worldmodel_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DataWrapper::GetMetadata() const {
  protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_messages_5fparsian_5fsimurosot_5fdata_5fwrapper_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Header* Arena::CreateMaybeMessage< ::Header >(Arena* arena) {
  return Arena::CreateInternal< ::Header >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::DataWrapper* Arena::CreateMaybeMessage< ::DataWrapper >(Arena* arena) {
  return Arena::CreateInternal< ::DataWrapper >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
